'use strict';

angular.module('icestudio')
    .service('boards', function() {

      this.getBoards = function() {
        return [
          { id: 'icezum', label: 'Icezum' },
          { id: 'icestick', label: 'iCEstick' },
          { id: 'go-board', label: 'Go board' },
		  { id: 'iCE40-HX8K', label: 'iCE40-HX8K' }
        ]
      };

      this.selectedBoard = this.getBoards()[0];

      this.selectBoard = function(id) {
        var boards = this.getBoards();
        for (var i in boards) {
          if (id == boards[i].id) {
            this.selectedBoard = boards[i];
            break;
          }
        }
      };

      this.pinouts = {};

      this.pinouts['icezum'] = [
        { name: 'LED0', value: '95' },
        { name: 'LED1', value: '96' },
        { name: 'LED2', value: '97' },
        { name: 'LED3', value: '98' },
        { name: 'LED4', value: '99' },
        { name: 'LED5', value: '101' },
        { name: 'LED6', value: '102' },
        { name: 'LED7', value: '104' },
        { name: 'SW1', value: '10' },
        { name: 'SW2', value: '11' },
        { name: 'D13', value: '144' },
        { name: 'D12', value: '143' },
        { name: 'D11', value: '142' },
        { name: 'D10', value: '141' },
        { name: 'D9', value: '139' },
        { name: 'D8', value: '138' },
        { name: 'D7', value: '112' },
        { name: 'D6', value: '113' },
        { name: 'D5', value: '114' },
        { name: 'D4', value: '115' },
        { name: 'D3', value: '116' },
        { name: 'D2', value: '117' },
        { name: 'D1', value: '118' },
        { name: 'D0', value: '119' },
        { name: 'DD0', value: '78' },
        { name: 'DD1', value: '79' },
        { name: 'DD2', value: '80' },
        { name: 'DD3', value: '81' },
        { name: 'DD4', value: '88' },
        { name: 'DD5', value: '87' },
        { name: 'GP0', value: '37' },
        { name: 'GP1', value: '38' },
        { name: 'GP2', value: '39' },
        { name: 'GP3', value: '41' },
        { name: 'GP4', value: '42' },
        { name: 'GP5', value: '43' },
        { name: 'GP6', value: '49' },
        { name: 'GP7', value: '50' },
        { name: 'ADC_SCL', value: '91' },
        { name: 'ADC_SDA', value: '90' },
        { name: 'ADC_INT', value: '93' },
        { name: 'CLK', value: '21' },
        { name: 'RES', value: '66' },
        { name: 'DONE', value: '65' },
        { name: 'SS', value: '71' },
        { name: 'MISO', value: '67' },
        { name: 'MOSI', value: '68' },
        { name: 'SCK', value: '70' },
        { name: 'DCD', value: '1' },
        { name: 'DSR', value: '2' },
        { name: 'DTR', value: '3' },
        { name: 'CTS', value: '4' },
        { name: 'RTS', value: '7' },
        { name: 'TX', value: '8' },
        { name: 'RX', value: '9' }
      ];

      this.pinouts['icestick'] = [
        { name: 'D1', value: '99' },
        { name: 'D2', value: '98' },
        { name: 'D3', value: '97' },
        { name: 'D4', value: '96' },
        { name: 'D5', value: '95' },
        { name: 'IrDA_TX', value: '105' },
        { name: 'IrDA_RX', value: '106' },
        { name: 'SD', value: '107' },
        { name: 'PMOD1', value: '78' },
        { name: 'PMOD2', value: '79' },
        { name: 'PMOD3', value: '80' },
        { name: 'PMOD4', value: '81' },
        { name: 'PMOD7', value: '87' },
        { name: 'PMOD8', value: '88' },
        { name: 'PMOD9', value: '90' },
        { name: 'PMOD10', value: '91' },
        { name: 'TR3', value: '112' },
        { name: 'TR4', value: '113' },
        { name: 'TR5', value: '114' },
        { name: 'TR6', value: '115' },
        { name: 'TR7', value: '116' },
        { name: 'TR8', value: '117' },
        { name: 'TR9', value: '118' },
        { name: 'TR10', value: '119' },
        { name: 'BR3', value: '62' },
        { name: 'BR4', value: '61' },
        { name: 'BR5', value: '60' },
        { name: 'BR6', value: '56' },
        { name: 'BR7', value: '48' },
        { name: 'BR8', value: '47' },
        { name: 'BR9', value: '45' },
        { name: 'BR10', value: '44' },
        { name: 'CLK', value: '21' },
        { name: 'RES', value: '66' },
        { name: 'DONE', value: '65' },
        { name: 'SS', value: '71' },
        { name: 'MISO', value: '67' },
        { name: 'MOSI', value: '68' },
        { name: 'SCK', value: '70' },
        { name: 'DCD', value: '1' },
        { name: 'DSR', value: '2' },
        { name: 'DTR', value: '3' },
        { name: 'CTS', value: '4' },
        { name: 'RTS', value: '7' },
        { name: 'TX', value: '8' },
        { name: 'RX', value: '9' }
      ];

      this.pinouts['go-board'] = [
        { name: 'LED1', value: '56' },
        { name: 'LED2', value: '57' },
        { name: 'LED3', value: '59' },
        { name: 'LED4', value: '60' },
        { name: 'SW1', value: '53' },
        { name: 'SW2', value: '51' },
        { name: 'SW3', value: '54' },
        { name: 'SW4', value: '52' },
        { name: 'S1_A', value: '3' },
        { name: 'S1_B', value: '4' },
        { name: 'S1_C', value: '93' },
        { name: 'S1_D', value: '91' },
        { name: 'S1_E', value: '90' },
        { name: 'S1_F', value: '1' },
        { name: 'S1_G', value: '2' },
        { name: 'S2_A', value: '100' },
        { name: 'S2_B', value: '99' },
        { name: 'S2_C', value: '97' },
        { name: 'S2_D', value: '95' },
        { name: 'S2_E', value: '94' },
        { name: 'S2_F', value: '8' },
        { name: 'S2_G', value: '96' },
        { name: 'CLK', value: '15' },
        { name: 'RX', value: '73' },
        { name: 'TX', value: '74' },
        { name: 'VGA_HS', value: '26' },
        { name: 'VGA_VS', value: '27' },
        { name: 'VGA_R0', value: '36' },
        { name: 'VGA_R1', value: '37' },
        { name: 'VGA_R2', value: '40' },
        { name: 'VGA_G0', value: '29' },
        { name: 'VGA_G1', value: '30' },
        { name: 'VGA_G2', value: '33' },
        { name: 'VGA_B0', value: '28' },
        { name: 'VGA_B1', value: '41' },
        { name: 'VGA_B2', value: '42' },
        { name: 'PMOD1', value: '65' },
        { name: 'PMOD2', value: '64' },
        { name: 'PMOD3', value: '63' },
        { name: 'PMOD4', value: '62' },
        { name: 'PMOD7', value: '78' },
        { name: 'PMOD8', value: '79' },
        { name: 'PMOD9', value: '80' },
        { name: 'PMOD10', value: '81' }
      ];

      this.pinouts['iCE40-HX8K'] = [
        { name: 'D9', value: 'B5' },
        { name: 'D8', value: 'B4' },
		{ name: 'D7', value: 'A2' },
		{ name: 'D6', value: 'A1' },
		{ name: 'D5', value: 'C5' },
		{ name: 'D4', value: 'C4' },
		{ name: 'D3', value: 'B3' },
		{ name: 'D2', value: 'C3' },
		{ name: 'B1', value: 'B1' },
		{ name: 'B2', value: 'B2' },
		{ name: 'C1', value: 'C1' },
        { name: 'C2', value: 'C2' },
        { name: 'D1', value: 'D1' },
        { name: 'D2', value: 'D2' },
        { name: 'E2', value: 'E2' },
        { name: 'F1', value: 'F1' },
        { name: 'F2', value: 'F2' },
        { name: 'G1', value: 'G1' },
        { name: 'G2', value: 'G2' },
        { name: 'H1', value: 'H1' },
        { name: 'H2', value: 'H2' },
        { name: 'J3', value: 'J3' },
        { name: 'J2', value: 'J2' },
        { name: 'J1', value: 'J1' },
        { name: 'K3', value: 'K3' },
        { name: 'K1', value: 'K1' },
        { name: 'L3', value: 'L3' },
        { name: 'L1', value: 'L1' },
        { name: 'M2', value: 'M2' },
        { name: 'M1', value: 'M1' },
        { name: 'N3', value: 'N3' },
        { name: 'N2', value: 'N2' },
        { name: 'P1', value: 'P1' },
        { name: 'P2', value: 'P2' },
        { name: 'R1', value: 'R1' },
        { name: 'T1', value: 'T1' },
        { name: 'T2', value: 'T2' },
        { name: 'R2', value: 'R2' },
        { name: 'T3', value: 'T3' },
        { name: 'R3', value: 'R3' },
        { name: 'R4', value: 'R4' },
        { name: 'T5', value: 'T5' },
        { name: 'R5', value: 'R5' },
        { name: 'T6', value: 'T6' },
        { name: 'R6', value: 'R6' },
        { name: 'T7', value: 'T7' },
        { name: 'T8', value: 'T8' },
        { name: 'T9', value: 'T9' },
        { name: 'R9', value: 'R8' },
        { name: 'P8', value: 'P8' },
        { name: 'P9', value: 'P9' },
        { name: 'T10', value: 'T10' },
        { name: 'R10', value: 'R10' },
        { name: 'T11', value: 'T11' },
        { name: 'P10', value: 'P10' },
        { name: 'N12', value: 'N12' },
        { name: 'P13', value: 'P13' },
        { name: 'T13', value: 'T13' },
        { name: 'T14', value: 'T14' },
        { name: 'T15', value: 'T15' },
        { name: 'T16', value: 'T16' },
        { name: 'R16', value: 'R16' },
        { name: 'C16', value: 'C16' },
        { name: 'B16', value: 'B16' },
        { name: 'D16', value: 'D16' },
        { name: 'D14', value: 'D14' },
        { name: 'E16', value: 'E16' },
        { name: 'D15', value: 'D15' },
        { name: 'F16', value: 'F16' },
        { name: 'E14', value: 'E14' },
        { name: 'G16', value: 'G16' },
        { name: 'F15', value: 'F15' },
        { name: 'H16', value: 'H16' },
        { name: 'G15', value: 'G15' },
        { name: 'J15', value: 'J15' },
        { name: 'H14', value: 'H14' },
        { name: 'G14', value: 'G14' },
        { name: 'F14', value: 'F14' },
        { name: 'K14', value: 'K14' },
        { name: 'J14', value: 'J14' },
        { name: 'K15', value: 'K15' },
        { name: 'K16', value: 'K16' },
        { name: 'M16', value: 'M16' },
        { name: 'L16', value: 'L16' },
        { name: 'N16', value: 'N16' },
        { name: 'M15', value: 'M15' },
        { name: 'P16', value: 'P16' },
        { name: 'P15', value: 'P15' },
        { name: 'R15', value: 'R15' },
        { name: 'A2', value: 'A2' },
        { name: 'A1', value: 'A1' },
        { name: 'B4', value: 'B4' },
        { name: 'B3', value: 'B3' },
        { name: 'B5', value: 'B5' },
        { name: 'C3', value: 'C3' },
        { name: 'A5', value: 'A5' },
        { name: 'C4', value: 'C4' },
        { name: 'B6', value: 'B6' },
        { name: 'C5', value: 'C5' },
        { name: 'A6', value: 'A6' },
        { name: 'C6', value: 'C6' },
        { name: 'B7', value: 'B7' },
        { name: 'C7', value: 'C7' },
        { name: 'B8', value: 'B8' },
        { name: 'A7', value: 'A7' },
        { name: 'A9', value: 'A9' },
        { name: 'B9', value: 'B9' },
        { name: 'A10', value: 'A10' },
        { name: 'C9', value: 'C9' },
        { name: 'A11', value: 'A11' },
        { name: 'B10', value: 'B10' },
        { name: 'B12', value: 'B12' },
        { name: 'B11', value: 'B11' },
        { name: 'B13', value: 'B13' },
        { name: 'B14', value: 'B14' },
        { name: 'A15', value: 'A15' },
        { name: 'B15', value: 'B15' },
        { name: 'A16', value: 'A16' }
	   ]

      this.getPinout = function() {
        return this.pinouts[this.selectedBoard.id];
      }

    });
