// Code generated by Icestudio 0.3.3-rc
// Tue, 24 Jul 2018 16:04:48 GMT

`default_nettype none

module main #(
 parameter v30f40a = 20
) (
 input vb8a806,
 input ve0befb,
 input vclk,
 output v32232e,
 output v1d1af8,
 output [3:0] v6a65cd,
 output [0:1] vinit
);
 localparam p0 = v30f40a;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire [0:3] w5;
 wire w6;
 assign w1 = vb8a806;
 assign w2 = ve0befb;
 assign v32232e = w3;
 assign v1d1af8 = w4;
 assign v6a65cd = w5;
 assign w6 = vclk;
 assign w4 = w3;
 v3e6c24 vc4b1b9 (
  .v608bd9(w3)
 );
 main_v4549a6 #(
  .N(p0)
 ) v4549a6 (
  .ena(w1),
  .rst(w2),
  .out(w5),
  .clk(w6)
 );
 assign vinit = 2'b00;
endmodule

module v3e6c24 (
 output v608bd9
);
 wire w0;
 assign v608bd9 = w0;
 v3e6c24_v68c173 v68c173 (
  .v(w0)
 );
endmodule

module v3e6c24_v68c173 (
 output v
);
 // Bit 1
 
 assign v = 1'b1;
endmodule

module main_v4549a6 #(
 parameter N = 0
) (
 input clk,
 input ena,
 input rst,
 output [3:0] out
);
 // Counter 4 bits
 // @include div.v
 
 wire trig; reg out;
 
 DIV #(N) div (
   .clk(clk),
   .out(trig)
 );
 
 always @(posedge trig) begin
   if (rst == 1)
     out <= 0;
   else if (ena == 1)
     out <= out + 1;
 end
 
endmodule
